### ISSUE TITLE
Error: Field name 'size' found in Product is a reserved keyword

### ISSUE THREAD

**Issue by EnziinSystem** [adyen-examples/adyen-java-react-ecommerce-example#5]
Import entities:
```
jhipster import-jdl app.jdl
```
The error message:
```
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing import-jdl shop.jdl
INFO! The JDL is being parsed.
Error: Field name 'size' found in Product is a reserved keyword, as it is used by Spring for pagination in the URL.
Error while parsing applications and entities from the JDL Error: Field name 'size' found in Product is a reserved keyword, as it is used by Spring for pagination in the URL.
Error: Field name 'size' found in Product is a reserved keyword, as it is used by Spring for pagination in the URL.
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:118:15
    at Array.forEach (<anonymous>)
    at checkForFieldErrors (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:111:28)
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:102:7
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/models/jdl-object.js:140:7
    at Array.forEach (<anonymous>)
    at JDLObject.forEachEntity (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/models/jdl-object.js:138:32)
    at checkForEntityErrors (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:85:15)
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:61:9
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/models/jdl-object.js:75:7
    at Array.forEach (<anonymous>)
    at JDLObject.forEachApplication (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/models/jdl-object.js:73:36)
    at Object.checkForErrors (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:55:17)
    at checkForErrors (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/jdl-importer.js:193:13)
    at Object.import (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/jdl-importer.js:110:7)
    at JDLProcessor.importJDL (/home/kevin/Desktop/shop/node_modules/generator-jhipster/cli/import-jdl.js:199:43)
Error during import-jdl: Error: Field name 'size' found in Product is a reserved keyword, as it is used by Spring for pagination in the URL.
Error: Field name 'size' found in Product is a reserved keyword, as it is used by Spring for pagination in the URL.
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:118:15
    at Array.forEach (<anonymous>)
    at checkForFieldErrors (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:111:28)
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:102:7
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/models/jdl-object.js:140:7
    at Array.forEach (<anonymous>)
    at JDLObject.forEachEntity (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/models/jdl-object.js:138:32)
    at checkForEntityErrors (/home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:85:15)
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/validators/jdl-with-application-validator.js:61:9
    at /home/kevin/Desktop/shop/node_modules/generator-jhipster/jdl/models/jdl-object.js:75:7
    at Array.forEach (<anonymous>)
```

**Comment by deepu105** [comment]
Hi, the size was made a reserved keyword in latest version of JHipster. You
can rename that field to productSize and should work

**Comment by EnziinSystem** [comment]
Please update for JHipster 7.0.0
Thanks.

**Comment by deepu105** [comment]
The example is updated now
